### ISSUE TITLE
Prebuilt skia-canvas node module does not work on macOS 10.13

### ISSUE THREAD

**Issue by Sakari369** [samizdatco/skia-canvas#22]
Just wanted to let you know, that the prebuilt node library does not work on macOS 10.13.

Doing 

```
npm install skia-canvas
```

Which installs the 0.9.22 version, and then trying the example code provided in the readme results in this error message:

```
sakari@Sakaris-MacBook-Pro ~/d/t/skia_canvas> node test.js
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/sakari/dvl/test/skia_canvas/node_modules/skia-canvas/lib/v6/index.node (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/sakari/dvl/test/skia_canvas/node_modules/skia-canvas/lib/v6/index.node (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

fish: Job 1, 'node test.js' terminated by signal SIGABRT (Abort)
```

So probably minimum required macOS version should be indicated as 10.15 or maybe you can try and compile against an older framework, I think it could be possible by just setting the target macOS SDK to 10.13 for example.

Many people still use macOS High Sierra 10.13 as it is the last version supported by older hardware. So maybe skia-canvas could work well on 10.13 SDK also ? Not sure.

At least documentation should say minimum required version of macOS then.
Thanks! I will try later with a newer macOS, currently using my older one ..

**Comment by Sakari369** [comment]
Tried to build with 

```
npm run build
```

But this fails with libskia_bindings library prebuilt package being built against 10.15 SDK also.

```
          ld: warning: object file (/Users/sakari/dvl/test/skia_canvas/node_modules/skia-canvas/target/debug/deps/libskia_bindings-87714c7cd383831d.rlib(libicu.ruleiter.o)) was built for newer OSX version (10.15) than being linked (10.13)
          ld: warning: object file (/Users/sakari/dvl/test/skia_canvas/node_modules/skia-canvas/target/debug/deps/libskia_bindings-87714c7cd383831d.rlib(libicu.unames.o)) was built for newer OSX version (10.15) than being linked (10.13)
          ld: warning: object file (/Users/sakari/dvl/test/skia_canvas/node_modules/skia-canvas/target/debug/deps/libskia_bindings-87714c7cd383831d.rlib(libicu.uhash_us.o)) was built for newer OSX version (10.15) than being linked (10.13)
          ld: warning: object file (/Users/sakari/dvl/test/skia_canvas/node_modules/skia-canvas/target/debug/deps/libskia_bindings-87714c7cd383831d.rlib(libicu.locresdata.o)) was built for newer OSX version (10.15) than being linked (10.13)
          ld: warning: object file (/Users/sakari/dvl/test/skia_canvas/node_modules/skia-canvas/target/debug/deps/libskia_bindings-87714c7cd383831d.rlib(libicu.ustrfmt.o)) was built for newer OSX version (10.15) than being linked (10.13)
          ld: warning: object file (/Users/sakari/dvl/test/skia_canvas/node_modules/skia-canvas/target/debug/deps/libskia_bindings-87714c7cd383831d.rlib(libicu.utrie.o)) was built for newer OSX version (10.15) than being linked (10.13)
          Undefined symbols for architecture x86_64:
            "____chkstk_darwin", referenced from:
                TightBounds(SkPath const&, SkRect*) in libskia_bindings-87714c7cd383831d.rlib(libskia.SkPathOpsTightBounds.o)
                OpDebug(SkPath const&, SkPath const&, SkPathOp, SkPath*) in libskia_bindings-87714c7cd383831d.rlib(libskia.SkPathOpsOp.o)
                SimplifyDebug(SkPath const&, SkPath*) in libskia_bindings-87714c7cd383831d.rlib(libskia.SkPathOpsSimplify.o)
                SkCopyStreamToData(SkStream*) in libskia_bindings-87714c7cd383831d.rlib(libskia.SkStream.o)
                SkStreamCopy(SkWStream*, SkStream*) in libskia_bindings-87714c7cd383831d.rlib(libskia.SkStream.o)
                SkPerlinNoiseShaderImpl::PaintingData::init(float) in libskia_bindings-87714c7cd383831d.rlib(libskia.SkPerlinNoiseShader.o)
                AutoCleanPng::decodeBounds() in libskia_bindings-87714c7cd383831d.rlib(png_decode.SkPngCodec.o)
                ...
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: aborting due to previous error

error: could not compile `skia-canvas`

To learn more, run the command again with --verbose.
Did not copy "cdylib:skia-canvas"
npm ERR! code ELIFECYCLE
npm ERR! errno 101
npm ERR! skia-canvas@0.9.22 build: `cargo-cp-artifact -nc lib/v6/index.node -- cargo build --message-format=json-render-diagnostics`
npm ERR! Exit status 101
npm ERR!
npm ERR! Failed at the skia-canvas@0.9.22 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sakari/.npm/_logs/2021-06-30T08_49_39_262Z-debug.log
```

Not sure how I would go on rebuilding this dependency.

**Comment by Sakari369** [comment]
My motivation for testing out this, would be to maybe replace node-canvas library with skia-canvas, but for that I would require at least 10.13 version support as a minimum, as we are building an electron based application that would require a native canvas library.

I will test out this first on my newer laptop to see if it works, just wanted to report this.

**Comment by samizdatco** [comment]
Thanks for letting me know about that. I experimented with different `MACOSX_DEPLOYMENT_TARGET` values in ef165d2df69fa21b2cc2d5a3850eb7d42ba67a32 and was able to get it to compile successfully targeting Sierra (10.12) and later.

You can download a pre-release version of the resulting binary [here](https://skia-canvas.s3.us-east-1.amazonaws.com/v0.9.23b/darwin-x64-napi-v6.tar.gz) for now if you have a chance to test it on your system. Try placing the `index.node` file from the archive in the `skia-canvas/lib/v6` folder then running these commands from the repository root:

```console
npm ci
npm run test
```

**Comment by Sakari369** [comment]
@samizdatco Hey thanks for reply.
I tried running npm ci, and npm run test, the ci passes but when I run 'npm run test' it says

```
> skia-canvas@0.9.22 test /Users/sakari/dvl/test/skia_canvas/node_modules/skia-canvas
> jest

No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
No files found in /Users/sakari/dvl/test/skia_canvas/node_modules/skia-canvas.
Make sure Jest's configuration does not exclude this directory.
To set up Jest, make sure a package.json file exists.
Jest Documentation: facebook.github.io/jest/docs/configuration.html
Pattern:  - 0 matches
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! skia-canvas@0.9.22 test: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the skia-canvas@0.9.22 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sakari/.npm/_logs/2021-06-30T19_00_53_001Z-debug.log
```

I tried just copying the example js from the readme to my test directory root, and running from there with

```
node test.js
```

Where this directory has node_modules/skia-canvas and the binary you linked placed under lib/v6, but no luck, still the same error:

```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/sakari/dvl/test/skia_canvas/node_modules/skia-canvas/lib/v6/index.node
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/sakari/dvl/test/skia_canvas/node_modules/skia-canvas/lib/v6/index.node
  Expected in: /usr/lib/libSystem.B.dylib

fish: Job 1, 'node test.js' terminated by signal SIGABRT (Abort)
```

**Comment by samizdatco** [comment]
Thanks for your help testing that out. Given that it didn't work, my suspicion is that the Skia libraries themselves will also need to be compiled with an older deployment target. I've opened an issue with the `rust-skia` project, so let's see what they think the solution might be: https://github.com/rust-skia/rust-skia/issues/538

**Comment by Sakari369** [comment]
> Thanks for your help testing that out. Given that it didn't work, my suspicion is that the Skia libraries themselves will also need to be compiled with an older deployment target. I've opened an issue with the `rust-skia` project, so let's see what they think the solution might be: [rust-skia/rust-skia#538](https://github.com/rust-skia/rust-skia/issues/538)

Thanks! Yeah, I managed to compile rust-skia just fine on this 10.13 machine. Haven't figured out yet how to replace the version from cargo with the precompiled one, my Rust -knowledge on this subject is shallow. So at least it should be possible.

Thanks for the help! Current node-canvas version comes with a whopping 70 megabytes of external libraries (including SVG support built with rsvg) that it depends on. It's based on the cairo renderer, not Skia that Chromium uses. 

We have an application (https://www.OmniGeometry.com) that exports art created with the app to PDF and SVG using node-canvas, but would be happier if the output exactly matched that of the Skia -libraries and also not depended on 70 megabytes of .dylibs needed to ship with the node module.

Willing to help on this subject also if I can some way.

**Comment by Sakari369** [comment]
Oh yeah got the library running on my Big Sur machine, the tests also, seems the test was failing because I was running it from under node_modules/skia-canvas, renaming node_modules to something else did not match it's builtin ignore pattern it seems and the tests could be ran.

**Comment by samizdatco** [comment]
The [0.9.24 release](https://github.com/samizdatco/skia-canvas/releases/tag/v0.9.24) has some changes to try add support for 10.13. Would you mind testing it and letting me know whether it works for you?

**Comment by Sakari369** [comment]
> The [0.9.24 release](https://github.com/samizdatco/skia-canvas/releases/tag/v0.9.24) has some changes to try add support for 10.13. Would you mind testing it and letting me know whether it works for you?

Great! I will test soon and report back to you. Thanks for requesting this support in rust-skia and making it possible :)

**Comment by Sakari369** [comment]
Tested on macOS 10.13 64-bit with v0.9.24 by installing the node module, and ran the test.js code you provided:

```js 
const fs = require('fs');

const {Canvas, loadImage} = require('skia-canvas'),
      rand = n => Math.floor(n * Math.random());

let canvas = new Canvas(600, 600),
    ctx = canvas.getContext("2d"),
    {width, height} = canvas;

// draw a sea of blurred dots filling the canvas
ctx.filter = 'blur(12px) hue-rotate(20deg)'
for (let i=0; i<800; i++){
  ctx.fillStyle = `hsl(${rand(40)}deg, 80%, 50%)`
  ctx.beginPath()
  ctx.arc(rand(width), rand(height), rand(20)+5, 0, 2*Math.PI)
  ctx.fill()
}

// mask all of the dots that don't overlap with the text
ctx.filter = 'none'
ctx.globalCompositeOperation = 'destination-in'
ctx.font='italic 480px Times, DejaVu Serif'
ctx.textAlign = 'center'
ctx.textBaseline = 'top'
ctx.fillText('¶', width/2, 0)

// draw a background behind the clipped text
ctx.globalCompositeOperation = 'destination-over'
ctx.fillStyle = '#182927'
ctx.fillRect(0,0, width,height)

// save the graphic...
canvas.saveAs("pilcrow.png")
```

Works succesfully! 👍 🙂
